{
 "title": "Wind Tunnel",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "esphome_fan_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Downforce",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esphome_sensor_value{job=\"wind-tunnel\", id=\"load_cell\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "esphome_fan_speed{job=\"wind-tunnel\", id=\"fan\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downforce",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"load_cell\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}